# Generated by Django 4.2.16 on 2024-10-27 11:47

import RegularExam.authors.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='passcode',
            field=models.CharField(max_length=6, validators=[RegularExam.authors.validators.validate_passcode]),
        ),
    ]
